sudo: false
language: java
jdk:
  - oraclejdk8
services:
  - docker

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - docker run -v=$(pwd):/app --workdir=/app/frontend coala/base coala --ci
  - ./gradlew test build

after_success:
  - bash <(curl -s https://codecov.io/bash)
