spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      path: /h2
      enabled: false
  datasource:
    url: jdbc:h2:file:~/changewatcher.db
    username: changewatcher_ci
    driver-class: org.h2.Driver